config/routes.rb
Rails.application.routes.draw do
  root :to => "animals#index"
  resources :animals
   get '/about' => "about#index"
   post '/animals/:id/edit' => "animals#update"
end

app/models/animal.rb
class Animal < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  def index
    @animals = Animal.all
  end

  def show
    @animal = Animal.find(params[:id])
  end

  def new
  end

  def create
    @animal = Animal.new(animal_params)

    if @animal.save
      redirect_to @animal
    else
      render 'new'
    end
  end

  def update
    @animal = Animal.find(params[:id])

    if @animal.update(animal_params)
      redirect_to @animal
    else
      render 'edit'
    end
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy

    redirect_to animals_path
  end

  private
    def animal_params
      params.require(:animal).permit(:name,:latin,:division,:desc)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<% content_for :title, "AnimalApp: About" %>

<h1>O mnie</h1>
<h3>Mariusz Mazepa (zaliczenie)</h3>

<table class="table">
  <thead>
    <tr id="table3">
      <th>Ruby</th>
      <th>Rails</th>
      <th>Baza</th>
      <th>Framework</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>2.4.0</td>
      <td>5.0.2</td>
      <td>
        <b>Lokalnie:</b> SQLite3<br/>
        <b>Heroku:</b> PostgreSQL
      </td>
      <td>Bootstrap</td>
    </tr>
  </tbody>
</table>

<p>
  Niniejsza aplikacja będzie wyświetlać dane z bazy zwierząt oraz
  umożliwiać zarządzanie nimi (dodawanie, edycja, usuwanie).
</p>

<h3>Użyte gemy</h3>
<table class="table">
  <thead>
    <tr id="table4">
      <th>L.P.</th>
      <th>Nazwa gemu</th>
      <th>Opis gemu</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>Paperclip</td>
      <td>Przesyłanie plików, na przykład obrazków. <b>(faza testów)</b></td>
    </tr>
  </tbody>
</table>

app/views/animals/_form.html.erb
<%= form_for :animal, url: animals_path do |f| %>

  <p>
    <%= f.label "Gatunek" %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label "Łacina" %><br>
    <%= f.text_field :latin %>
  </p>

  <p>
    <%= f.label "Gromada" %><br>
    <%= f.select :division, ['', 'Ssaki', 'Ptaki', 'Płazy', 'Gady', 'Ryby', 'Owady', 'Pajęczaki'] %>
  </p>

  <p>
    <%= f.label "Opis" %><br>
    <%= f.text_area :desc, size: "75x5" %>
  </p>

  <p>
    <%= f.submit "Zapisz Zwierze", class: "btn btn-success" %>
  </p>

<% end %>

app/views/animals/_form2.html.erb
<%= form_for :animal, url: edit_animal_path do |f| %>

  <p>
    <%= f.label "Gatunek" %><br>
    <%= f.text_field :name, :value => Animal.find(params[:id]).name %>
  </p>

  <p>
    <%= f.label "Łacina" %><br>
    <%= f.text_field :latin, :value => Animal.find(params[:id]).latin %>
  </p>

  <p>
    <%= f.label "Gromada" %><br>
    <%=
      f.select :division,
      ['', 'Ssaki', 'Ptaki', 'Płazy', 'Gady', 'Ryby', 'Owady', 'Pajęczaki'],
      :selected => Animal.find(params[:id]).division
    %>
  </p>

  <p>
    <%= f.label "Opis" %><br>
    <%=
      f.text_area :desc,
      :value => Animal.find(params[:id]).desc.split.join(' '),
      size: "75x5"
    %>
  </p>

  <p>
    <%= f.submit "Zapisz Zwierze", class: "btn btn-success" %>
  </p>

<% end %>

app/views/animals/edit.html.erb
<%- model_class = Animal -%>

<% content_for :title, "AnimalApp: Edit" %>

<h1>Edycja zwierzęcia</h1>

<%= render 'form2' %>

<%= link_to 'Powrót', animals_path, class: "btn btn-primary" %>

app/views/animals/index.html.erb
<%- model_class = Animal -%>

<% content_for :title, "AnimalApp: Home" %>

<h1>Zwierzęta</h1>
<div class="container">
  <table class="table table-striped">
    <thead>
      <tr id="table1">
        <th>L.P.</th>
        <th>Gatunek</th>
        <th>Łacina</th>
        <th>Gromada</th>
        <th>Opis</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @animals.each_with_index do |animal, i| %>
        <tr>
          <td><%= (i+1) %></td>
          <td><%= animal.name %></td>
          <td><i><%= animal.latin %></i></td>
          <td><%= animal.division %></td>
          <td id="opis"><%= truncate(animal.desc, :length => 150) %></td>
          <td><%= link_to animal_path(animal.id),
                  method: :get,
                  class: "btn btn-xs" do %>
                <%= glyph 'info-sign' %>
              <%- end -%></td>
          <td><%= link_to edit_animal_path(animal.id),
                  method: :get,
                  class: "btn btn-xs" do %>
                <%= glyph 'pencil' %>
              <%- end -%></td>
          <td><%= link_to animal_path(animal.id),
                  method: :delete,
                  data: { confirm: "Jesteś pewien, że chcesz usunąć następującą pozycję?\n
                                    ID: " + animal.id.to_s + "
                                    GATUNEK: " + animal.name + "
                                    ŁACINA: " + animal.latin + "
                                    GROMADA: " + animal.division + "
                                    OPIS: " + truncate(animal.desc, :length => 25) },
                  class: "btn btn-xs" do %>
                <%= glyph 'remove' %>
              <%- end -%></td>
        </tr>
      <% end %>
    </tbody>
    <div align="right">
      <%= link_to 'Nowe zwierze', new_animal_path, class: 'btn btn-primary' %>
      <br/>
      <br/>
    </div>
  </table>
</div>

app/views/animals/new.html.erb
<%- model_class = Animal -%>

<% content_for :title, "AnimalApp: New" %>

<h1>Nowe Zwierze</h1>

<%= render 'form' %>

<%= link_to 'Powrót', animals_path, class: "btn btn-primary" %>

app/views/animals/show.html.erb
<%- model_class = Animal -%>

<% content_for :title, "AnimalApp: Show " + @animal.id.to_s  %>

<h1>Zwierze nr <%= @animal.id %></h1>

<table class="table">
  <thead>
    <tr id="table2">
      <th>ID</th>
      <th>Gatunek</th>
      <th>Łacina</th>
      <th>Gromada</th>
      <th>Opis</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @animal.id %></td>
      <td><%= @animal.name %></td>
      <td><i><%= @animal.latin %></i></td>
      <td><i><%= @animal.division %></i></td>
      <td id="opis"><%= @animal.desc %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edytuj', edit_animal_path(@animal), class: "btn btn-success" %>
<%= link_to 'Powrót', animals_path, class: "btn btn-primary" %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav id="header">
      <%= link_to image_tag("rails.png", :alt => "ruby on rails", :size => '50x55'), '/' %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Strona Główna",  '/' %></li>
        <li><%= link_to "O mnie", '/about' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
    </div>
  </body>
</html>